#!/usr/bin/env python3
import colors as c
import time  
c.clear_screen()
    
count_length = 0.387


for verse in range (5):


    for badger in range(12):
         time.sleep(count_length)
         print (c.blue + 'badger' + c.reset)


    for badger in range(2):
        time.sleep(count_length * 2)
        print(c.red + 'mushroom' + c.reset)
   
    c.clear_screen()

                                                                                                                                                                                                     
print('''.▄▄ ·  ▐ ▄  ▄▄▄· ▄ •▄ ▄▄▄ .▄▄ ▄▄ 
▐█ ▀. •█▌▐█▐█ ▀█ █▌▄▌▪▀▄.▀·██▌██▌
▄▀▀▀█▄▐█▐▐▌▄█▀▀█ ▐▀▀▄·▐▀▀▪▄▐█·▐█·
▐█▄▪▐███▐█▌▐█ ▪▐▌▐█.█▌▐█▄▄▌.▀ .▀ 
 ▀▀▀▀ ▀▀ █▪ ▀  ▀ ·▀  ▀ ▀▀▀  ▀  ▀ 
                                 
                                       ''')
