#!/usr/bin/env python3
reset = '\033[0m'
clear = '\033[H\033[2J'
import colors as c  
import time
weeks = 0
days = 0
hours = 0
minutes = 0
seconds = 0
hundredths = 0
print(clear)
try:
    while True:
        time.sleep(0.01)
        print(clear)
        print(c.red + '{} weeks {} days {}:{}:{}.{}'.format(weeks,days,hours,minutes,seconds,hundredths))
        '''
        print('minutes')
        print(minutes)
        print('seconds:')
        print(seconds)
        print('hundredths:')
        print(hundredths)
        '''
        hundredths +=1
        if hundredths == 100:
            seconds +=1
            hundredths = 0
        if seconds == 60:
            minutes +=1
            seconds = 0
        
        if minutes == 60:
            hours +=1
            minutes =0 
        
        if hours == 24:
            days +=1
            hours =0

        if days == 7:
            weeks +=1
            days =0

except KeyboardInterrupt:
    exit()

