#!/usr/bin/env python3
reset = '\033[0m'
clear = '\033[H\033[2J'

import time

hundredths = 1
print(clear)
while True:
    time.sleep(0.01)
    print(clear)
    print('[ctrl + c to stop]' + reset, end=': ')
    print(hundredths)
    hundredths +=1

