#!/usr/bin/env python3

import colors as c
import time

print(c.clear)
while True:

    for count in range(12):
        print(c.b + 'badger')
        time.sleep(0.5)

    for count in range(2):
        print(c.r + 'mushroom')
        time.sleep(0.8)

    print(c.clear)
